version: '2.1'

services:

  nginx:
    build: .
    container_name: nginx
    hostname: nginx
    restart: always
    logging:
      options:
        max-size: "30m"
        max-file: "2"
    volumes:
      - ./ssl:/etc/nginx/ssl
      - ./configs/defaults.inc:/etc/nginx/defaults.inc
      - ./configs/ga.inc:/etc/nginx/ga.inc
      - ./configs/ssl.inc:/etc/nginx/ssl.inc
      - ./configs/service.conf:/etc/nginx/service.conf
      - ./www:/www
      # ggstats
      - ../ggstats/nginx.inc:/etc/nginx/ggstats.inc
      - ../ggstats/web/static:/www/ggstats
      # gggalka
      - ../gggalka/nginx.inc:/etc/nginx/gggalka.inc
      - ../gggalka/www:/www/gggalka
      # dtkd
      - ../youtube2podcast/data/files:/www/dtkd
    networks:
      - nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      - TZ=UTC
      - LETSENCRYPT=${LETSENCRYPT}
      - LE_EMAIL=${LE_EMAIL}
      - LE_FQDN=${LE_FQDN}

networks:
  nginx:
